CREATE TABLE ISALUMNO (
  ISUSUARIO_DNI VARCHAR(9) NOT NULL,
  NOMBRE VARCHAR(40) NOT NULL,
  APELLIDO1 VARCHAR(40) NOT NULL,
  APELLIDO2 VARCHAR(40) NOT NULL,
  TELEFONO INT(9) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  DIRECCION VARCHAR(100) NULL,
  FECH_NACIMIENTO VARCHAR(10) NULL,
  SEXO VARCHAR(10) NULL,
  PRIMARY KEY(ISUSUARIO_DNI),
  INDEX ISALUMNO_FKIndex1(ISUSUARIO_DNI)
)
TYPE=InnoDB;

CREATE TABLE ISAREA (
  IDISAREA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(100) NULL,
  PRIMARY KEY(IDISAREA)
)
TYPE=InnoDB;

CREATE TABLE ISAULA (
  IDISAULA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NULL,
  CAPACIDAD INTEGER UNSIGNED NULL,
  LOCALIZACION VARCHAR(100) NULL,
  PRIMARY KEY(IDISAULA)
)
TYPE=InnoDB;

CREATE TABLE ISAVISOS (
  IDISAVISOS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  FECHA_AVISO VARCHAR(10) NULL,
  FECHA_CADUCIDAD VARCHAR(10) NULL,
  ASUNTO VARCHAR(255) NULL,
  TEXTO VARCHAR(255) NULL,
  ACTIVO CHAR(1) NULL,
  PRIMARY KEY(IDISAVISOS)
)
TYPE=InnoDB;

CREATE TABLE ISAVISOS_HAS_ISUSUARIO (
  ISAVISOS_IDISAVISOS INTEGER UNSIGNED NOT NULL,
  ISUSUARIO_DNI VARCHAR(9) NOT NULL,
  PRIMARY KEY(ISAVISOS_IDISAVISOS, ISUSUARIO_DNI),
  INDEX ISAVISOS_has_ISUSUARIO_FKIndex1(ISAVISOS_IDISAVISOS),
  INDEX ISAVISOS_has_ISUSUARIO_FKIndex2(ISUSUARIO_DNI)
)
TYPE=InnoDB;

CREATE TABLE ISCONTRATO (
  ISUSUARIO_DNI VARCHAR(9) NOT NULL,
  ISNOMINA_IDISNOMINA INTEGER UNSIGNED NOT NULL,
  TIPO VARCHAR(200) NULL,
  PRIMARY KEY(ISUSUARIO_DNI),
  INDEX ISCONTRATO_FKIndex1(ISUSUARIO_DNI),
  INDEX ISCONTRATO_FKIndex2(ISNOMINA_IDISNOMINA)
)
TYPE=InnoDB;

CREATE TABLE ISCURSO (
  IDISCURSO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ISPROFESOR_ISUSUARIO_DNI VARCHAR(9) NOT NULL,
  ISAREA_IDISAREA INTEGER UNSIGNED NOT NULL,
  NOMBRE VARCHAR(50) NULL,
  NUMERO_PLAZAS INTEGER UNSIGNED NULL,
  ESTADO VARCHAR(20) NULL,
  FECHA_INICIO VARCHAR(10) NULL,
  FECHA_FIN VARCHAR(10) NULL,
  PRECIO FLOAT NULL,
  PRIMARY KEY(IDISCURSO),
  INDEX ISCURSO_FKIndex2(ISAREA_IDISAREA),
  INDEX ISCURSO_FKIndex3(ISPROFESOR_ISUSUARIO_DNI)
)
TYPE=InnoDB;

CREATE TABLE ISCURSO_HAS_ISALUMNO (
  ISCURSO_IDISCURSO INTEGER UNSIGNED NOT NULL,
  ISALUMNO_ISUSUARIO_DNI VARCHAR(9) NOT NULL,
  ISFICHA_IDISFICHA INTEGER UNSIGNED NOT NULL,
  NOTA_FINAL FLOAT NULL,
  PRIMARY KEY(ISCURSO_IDISCURSO, ISALUMNO_ISUSUARIO_DNI),
  INDEX ISCURSO_has_ISALUMNO_FKIndex1(ISCURSO_IDISCURSO),
  INDEX ISCURSO_has_ISALUMNO_FKIndex2(ISALUMNO_ISUSUARIO_DNI),
  INDEX ISCURSO_HAS_ISALUMNO_FKIndex3(ISFICHA_IDISFICHA)
)
TYPE=InnoDB;

CREATE TABLE ISFICHA (
  IDISFICHA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOTAS VARCHAR(255) NULL,
  ANOTACIONES VARCHAR(255) NULL,
  NOTAS_EJERCICIOS FLOAT NULL,
  PRIMARY KEY(IDISFICHA)
)
TYPE=InnoDB;

CREATE TABLE ISHORARIO (
  IDISHORARIO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  L VARCHAR(10) NULL,
  M VARCHAR(10) NULL,
  X VARCHAR(10) NULL,
  J VARCHAR(10) NULL,
  V VARCHAR(10) NULL,
  PRIMARY KEY(IDISHORARIO)
)
TYPE=InnoDB;

CREATE TABLE ISHORARIO_HAS_ISAULA (
  ISHORARIO_IDISHORARIO INTEGER UNSIGNED NOT NULL,
  ISAULA_IDISAULA INTEGER UNSIGNED NOT NULL,
  ISCURSO_IDISCURSO INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ISHORARIO_IDISHORARIO, ISAULA_IDISAULA),
  INDEX ISHORARIO_has_ISAULA_FKIndex1(ISHORARIO_IDISHORARIO),
  INDEX ISHORARIO_has_ISAULA_FKIndex2(ISAULA_IDISAULA),
  INDEX ISHORARIO_has_ISAULA_FKIndex3(ISCURSO_IDISCURSO)
)
TYPE=InnoDB;

CREATE TABLE ISNOMINA (
  IDISNOMINA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CUENTA_INGRESOS VARCHAR(30) NULL,
  CANTIDAD FLOAT NULL,
  PRIMARY KEY(IDISNOMINA)
)
TYPE=InnoDB;

CREATE TABLE ISPROFESOR (
  ISUSUARIO_DNI VARCHAR(9) NOT NULL,
  ISAREA_IDISAREA INTEGER UNSIGNED NOT NULL,
  NOMBRE VARCHAR(40) NULL,
  APELLIDO1 VARCHAR(40) NULL,
  APELLIDO2 VARCHAR(40) NULL,
  TELEFONO INT(9) NULL,
  EMAIL VARCHAR(50) NULL,
  PRIMARY KEY(ISUSUARIO_DNI),
  INDEX ISPROFESOR_FKIndex1(ISUSUARIO_DNI),
  INDEX ISPROFESOR_FKIndex2(ISAREA_IDISAREA)
)
TYPE=InnoDB;

CREATE TABLE ISUSUARIO (
  DNI VARCHAR(9) NOT NULL,
  CONTRASENIA VARCHAR(20) NULL,
  PERFIL VARCHAR(10) NULL,
  PRIMARY KEY(DNI)
)
TYPE=InnoDB;


